### ISSUE TITLE
question about data loader

### ISSUE THREAD

**Issue by MASTERCHIEF343** [matsuren/octDPSNet#1]
Hi, thanks to your code.It's impressive to the combine the two resolution of the cost volume.But I have some problems with the code.I see that the sequence_folders.py may same as DPSNet.For data loader, I also test the DPSNet, but I found the paper writer only use two views for estimation(I print the index of the data loader, if there are three photos in one data file, the data loader will load data just like[0, 1], [1, 0], [2, 1]), and if I use all the images, the memory of CUDA will out.So is it true for what I think or I just feel wrong?

**Comment by matsuren** [comment]
Thank you for your comment!

`sequence_folders.py` is almost the same as the one in DPSNet except that we added the save and load JSON function to save time. 

Yes, we used only two views for training and testing in DeMoN datasets. However, we also used three views for testing in ETH3D dataset. From our experiences, two or three views for estimation seem good for OctDPSNet, and if you add more than four view images, the accuracy is getting worse for some reason in addition to extra GPU memory consumption.

Thanks,

**Comment by MASTERCHIEF343** [comment]
Oh, I see.But for I know, more views will enhance the photo-consistency(or other geometry constraint) between reference image and target images.So I will test some times to find why the accuray will decrease when use more than four images.Also I think this situation maybe not the problem of GPU,  do you select the view during training?Just like MVSNet.

**Comment by matsuren** [comment]
> more views will enhance the photo-consistency(or other geometry constraint) between reference image and target images

Yeah, you're right. In DPSNet paper, they reported that the more they use images, the better the accuracy they achieve. I guess one of the reasons for degrading accuracy is that the attention-based cost volume integration. Since we used only two view images for training, the cost volume integration might be optimized for a few images.


>Also I think this situation maybe not the problem of GPU, do you select the view during training?Just like MVSNet.

We don't select the view during training but at the beginning of the training.

**Comment by MASTERCHIEF343** [comment]
Thanks!
