### ISSUE TITLE
question about integration module

### ISSUE THREAD

**Issue by MASTERCHIEF343** [matsuren/octDPSNet#2]
Hi, I'm confused about the channel number in integration module.I see the lower cost volume is upsampled to the same size as higher cost voulme.Then in your code, you use class SpatialSELayerOct to concatenate both cost volume features.I see in your code, you first use torch.squeeze to delete the channel which number is one, is that the channel's name is feature Channel?Because I see in depth refinement, the channel is one, and you squeeze.Then the rest of dimension is [batch_size, depth, height, width], so you concatenate the lower and the higher feature.But in the paper, Figure 6 shows that is c/8.So in integration module, are you concatenating channel dimension or depth dimension?

**Comment by matsuren** [comment]
Hi,
I didn't concatenate the lower and the higher features of the cost volume. I added them up with some weight factors (Please see Eq.(7) in our paper). So, in SpatialSELayerOct, almost all calculations are for calculating the weight factors ($lamda$ in Eq.(7)).
I'm not sure if I answer your question correctly, so if you have any questions please feel free to ask me again.
Thanks!

**Comment by MASTERCHIEF343** [comment]
Sorry, I'm not good at english.Before add them up, you use Concat the lower and the higher to calculate the weight vector.So I just confused about this step.Do you conca on depth dimension?In oct_semodule.py, line 34.

**Comment by matsuren** [comment]
>Do you conca on depth dimension?In oct_semodule.py, line 34.

I see, this is your question. I concatenated the lower and the higher cost volumes along with depth dimension.

**Comment by MASTERCHIEF343** [comment]
thank you
