### ISSUE TITLE
size of depth map on ETH3d datasets

### ISSUE THREAD

**Issue by MASTERCHIEF343** [matsuren/octDPSNet#5]
Hi, Thank you for sharing the code!
I just have several problems.When I want to test ETH3d datasets on MVSNet, the output result is downsampled as 1/4 compare to the input images.So for test evaluation, should I resize the ground truth as the same size of prediction result?And in my experiment, I only used colmap to calculate the camera parameters and converted it to the right form for MVSNet, but the result was too bad.I would like to know if you use the provided camera parameters?

**Comment by matsuren** [comment]
Sorry for my late reply. 
I hope you've already found solutions.
